version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: >
      sh -c "
        # Create SSL directory
        mkdir -p /etc/nginx/ssl
        
        # Generate self-signed certificate if it doesn't exist
        if [ ! -f /etc/nginx/ssl/localhost.crt ]; then
          apk add --no-cache openssl
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout /etc/nginx/ssl/localhost.key \
            -out /etc/nginx/ssl/localhost.crt \
            -subj '/C=US/ST=Local/L=Local/O=Local/CN=localhost' \
            -addext 'subjectAltName=DNS:localhost,DNS:127.0.0.1,IP:127.0.0.1'
          echo 'Generated self-signed SSL certificate for localhost'
        fi
        
        # Start nginx
        nginx -g 'daemon off;'
      "